// <auto-generated />
using System;
using AddressBook.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AddressBook.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230128091323_label")]
    partial class label
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AddressBook.Entities.AddressLabel", b =>
                {
                    b.Property<int>("AddressLabelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressLabelId"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("AddressLabelId");

                    b.ToTable("AddressLabel");
                });

            modelBuilder.Entity("AddressBook.Entities.ChatLabel", b =>
                {
                    b.Property<int>("ChatLabelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChatLabelId"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ChatLabelId");

                    b.ToTable("ChatLabel");
                });

            modelBuilder.Entity("AddressBook.Entities.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StateId")
                        .HasColumnType("int");

                    b.HasKey("CityId");

                    b.HasIndex("StateId");

                    b.ToTable("City");
                });

            modelBuilder.Entity("AddressBook.Entities.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"));

                    b.Property<string>("Capital")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencySymbol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emoji")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmojiU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Iso3")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Native")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumericCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubRegion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tld")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("iso2")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("CountryId");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("AddressBook.Entities.EmailLabel", b =>
                {
                    b.Property<int>("EmailLabelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmailLabelId"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("EmailLabelId");

                    b.ToTable("EmailLabel");
                });

            modelBuilder.Entity("AddressBook.Entities.Label", b =>
                {
                    b.Property<int>("LabelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LabelId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("LabelId");

                    b.ToTable("Label");
                });

            modelBuilder.Entity("AddressBook.Entities.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonId"));

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonId");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("AddressBook.Entities.PersonAddress", b =>
                {
                    b.Property<int>("PersonAddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonAddressId"));

                    b.Property<int?>("AddressLabelId")
                        .HasColumnType("int");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Line1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Line2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("PostCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonAddressId");

                    b.HasIndex("AddressLabelId");

                    b.HasIndex("CityId");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonAddress");
                });

            modelBuilder.Entity("AddressBook.Entities.PersonChat", b =>
                {
                    b.Property<int>("PersonChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonChatId"));

                    b.Property<string>("Chat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ChatLabelId")
                        .HasColumnType("int");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("PersonChatId");

                    b.HasIndex("ChatLabelId");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonChat");
                });

            modelBuilder.Entity("AddressBook.Entities.PersonEmail", b =>
                {
                    b.Property<int>("PersonEmailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonEmailId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmailLabelId")
                        .HasColumnType("int");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("PersonEmailId");

                    b.HasIndex("EmailLabelId");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonEmail");
                });

            modelBuilder.Entity("AddressBook.Entities.PersonLabel", b =>
                {
                    b.Property<int>("PersonLabelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonLabelId"));

                    b.Property<int?>("LabelId")
                        .HasColumnType("int");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("PersonLabelId");

                    b.HasIndex("LabelId");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonLabel");
                });

            modelBuilder.Entity("AddressBook.Entities.PersonPhone", b =>
                {
                    b.Property<int>("PersonPhoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonPhoneId"));

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PhoneLabelId")
                        .HasColumnType("int");

                    b.HasKey("PersonPhoneId");

                    b.HasIndex("CountryId");

                    b.HasIndex("PersonId");

                    b.HasIndex("PhoneLabelId");

                    b.ToTable("PersonPhone");
                });

            modelBuilder.Entity("AddressBook.Entities.PersonWebsite", b =>
                {
                    b.Property<int>("PersonWebsiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonWebsiteId"));

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WebsiteLabelId")
                        .HasColumnType("int");

                    b.HasKey("PersonWebsiteId");

                    b.HasIndex("PersonId");

                    b.HasIndex("WebsiteLabelId");

                    b.ToTable("PersonWebsite");
                });

            modelBuilder.Entity("AddressBook.Entities.PhoneLabel", b =>
                {
                    b.Property<int>("PhoneLabelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhoneLabelId"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PhoneLabelId");

                    b.ToTable("PhoneLabel");
                });

            modelBuilder.Entity("AddressBook.Entities.State", b =>
                {
                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StateId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StateId");

                    b.HasIndex("CountryId");

                    b.ToTable("State");
                });

            modelBuilder.Entity("AddressBook.Entities.Timezone", b =>
                {
                    b.Property<int>("TimezoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TimezoneId"));

                    b.Property<string>("Abbreviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<int>("GmtOffset")
                        .HasColumnType("int");

                    b.Property<string>("GmtOffsetName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TimezoneId");

                    b.HasIndex("CountryId");

                    b.ToTable("Timezone");
                });

            modelBuilder.Entity("AddressBook.Entities.Translation", b =>
                {
                    b.Property<int>("TranslationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TranslationId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TranslationId");

                    b.HasIndex("CountryId");

                    b.ToTable("Translation");
                });

            modelBuilder.Entity("AddressBook.Entities.WebsiteLabel", b =>
                {
                    b.Property<int>("WebsiteLabelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WebsiteLabelId"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("WebsiteLabelId");

                    b.ToTable("WebsiteLabel");
                });

            modelBuilder.Entity("AddressBook.Entities.City", b =>
                {
                    b.HasOne("AddressBook.Entities.State", "State")
                        .WithMany("Cities")
                        .HasForeignKey("StateId");

                    b.Navigation("State");
                });

            modelBuilder.Entity("AddressBook.Entities.PersonAddress", b =>
                {
                    b.HasOne("AddressBook.Entities.AddressLabel", "AddressLabel")
                        .WithMany()
                        .HasForeignKey("AddressLabelId");

                    b.HasOne("AddressBook.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId");

                    b.HasOne("AddressBook.Entities.Person", "Person")
                        .WithMany("PersonAddresses")
                        .HasForeignKey("PersonId");

                    b.Navigation("AddressLabel");

                    b.Navigation("City");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("AddressBook.Entities.PersonChat", b =>
                {
                    b.HasOne("AddressBook.Entities.ChatLabel", "ChatLabel")
                        .WithMany()
                        .HasForeignKey("ChatLabelId");

                    b.HasOne("AddressBook.Entities.Person", "Person")
                        .WithMany("PersonChats")
                        .HasForeignKey("PersonId");

                    b.Navigation("ChatLabel");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("AddressBook.Entities.PersonEmail", b =>
                {
                    b.HasOne("AddressBook.Entities.EmailLabel", "EmailLabel")
                        .WithMany()
                        .HasForeignKey("EmailLabelId");

                    b.HasOne("AddressBook.Entities.Person", "Person")
                        .WithMany("PersonEmails")
                        .HasForeignKey("PersonId");

                    b.Navigation("EmailLabel");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("AddressBook.Entities.PersonLabel", b =>
                {
                    b.HasOne("AddressBook.Entities.Label", "Label")
                        .WithMany()
                        .HasForeignKey("LabelId");

                    b.HasOne("AddressBook.Entities.Person", "Person")
                        .WithMany("PersonLabels")
                        .HasForeignKey("PersonId");

                    b.Navigation("Label");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("AddressBook.Entities.PersonPhone", b =>
                {
                    b.HasOne("AddressBook.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.HasOne("AddressBook.Entities.Person", "Person")
                        .WithMany("PersonPhones")
                        .HasForeignKey("PersonId");

                    b.HasOne("AddressBook.Entities.PhoneLabel", "PhoneLabel")
                        .WithMany()
                        .HasForeignKey("PhoneLabelId");

                    b.Navigation("Country");

                    b.Navigation("Person");

                    b.Navigation("PhoneLabel");
                });

            modelBuilder.Entity("AddressBook.Entities.PersonWebsite", b =>
                {
                    b.HasOne("AddressBook.Entities.Person", "Person")
                        .WithMany("PersonWebsites")
                        .HasForeignKey("PersonId");

                    b.HasOne("AddressBook.Entities.WebsiteLabel", "WebsiteLabel")
                        .WithMany()
                        .HasForeignKey("WebsiteLabelId");

                    b.Navigation("Person");

                    b.Navigation("WebsiteLabel");
                });

            modelBuilder.Entity("AddressBook.Entities.State", b =>
                {
                    b.HasOne("AddressBook.Entities.Country", "Country")
                        .WithMany("States")
                        .HasForeignKey("CountryId");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("AddressBook.Entities.Timezone", b =>
                {
                    b.HasOne("AddressBook.Entities.Country", "Country")
                        .WithMany("Timezones")
                        .HasForeignKey("CountryId");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("AddressBook.Entities.Translation", b =>
                {
                    b.HasOne("AddressBook.Entities.Country", "Country")
                        .WithMany("Translations")
                        .HasForeignKey("CountryId");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("AddressBook.Entities.Country", b =>
                {
                    b.Navigation("States");

                    b.Navigation("Timezones");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("AddressBook.Entities.Person", b =>
                {
                    b.Navigation("PersonAddresses");

                    b.Navigation("PersonChats");

                    b.Navigation("PersonEmails");

                    b.Navigation("PersonLabels");

                    b.Navigation("PersonPhones");

                    b.Navigation("PersonWebsites");
                });

            modelBuilder.Entity("AddressBook.Entities.State", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
